### PR TITLE
Changed sync to be consistent across hosts

### PR DESCRIPTION
**Pull request by moore3071**
This should take care of part of #33, but we should argue Docker vs Vagrant

### CODE REVIEW

**Comment by vipermark7** [comment]
*shipit*

**Comment by J3RN** [comment]
I feel the disdainful eyes of Rubocop looking down at these double quotes.

**Comment by J3RN** [comment]
Also -- I hope that lines 12-16 can be changed to:
```
config.vm.synced_folder '.', '/home/vagrant/cwdg-website'
```
This should work (*hopefully*) across all major operating systems.

**Comment by moore3071** [comment]
Unfortunately after testing on my system, `config.vm.synced_folder '.', '/home/vagrant/cwdg-website'` didn't work, so Linux will maintain rsync. I did however forget to change the elif to else so we aren't *only* catering to Linux and Mac.

As far as the double quotes, I was simply making things consistent across the file, I can change them to single quotes though if Rubocop disapproves

**Comment by J3RN** [comment]
I'm saddened to hear that Vagrant hasn't yet come to it's senses regarding syncing on Linux.

It's an unofficial standard (as all are) in Ruby to use single quotes unless you need string interpolation (which only works with double quotes). Rubocop enforces this. I would appreciate the change in your next round of Vagrant changes.

**Pull request merged**
